---
project_name: nack

release:
  name_template: 'Release {{.Tag}}'
  draft: true
  skip_upload: true
  github:
    owner: nats-io
    name: nack

builds:
  - id: jetstream-controller
    main: ./cmd/jetstream-controller
    binary: jetstream-controller
    tags:
      - timetzdata
    env:
      - GO11MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
  - id: nats-boot-config
    main: ./cmd/nats-boot-config
    binary: nats-boot-config
    tags:
      - timetzdata
    env:
      - GO11MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
  - id: nats-server-config-reloader
    main: ./cmd/nats-server-config-reloader
    binary: nats-server-config-reloader
    tags:
      - timetzdata
    env:
      - GO11MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
