apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetstream-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jetstream-controller
  template:
    metadata:
      labels:
        name: jetstream-controller
    spec:
      serviceAccountName: jetstream-controller
      containers:
      - name: jsc
        image: connecteverything/jetstream-controller:0.1.0
        imagePullPolicy: IfNotPresent
        command:
        - /jetstream-controller
        - -s=nats://nats:4222
