---
apiVersion: jetstream.nats.io/v1
kind: Consumer
metadata:
  name: myconsumer
spec:
  servers:
  - nats://localhost:4222
  credentialsSecret:
    name: myncreds
    key: nats-myusr
  streamName: mystream
  durableName: myconsumer
