---
apiVersion: jetstream.nats.io/v1
kind: Stream
metadata:
  name: mystream
spec:
  servers:
  - nats://localhost:4222
  #credentials: myncreds
  name: mystream
  subjects: ["orders.*"]
  storage: memory
  maxAge: 1h
