---
apiVersion: v1
kind: Pod
metadata:
  name: jetstream-controller-pod
spec:
  serviceAccountName: jetstream-controller-service-account
  containers:
  - name: jetstream-controller
    image: {{.Values.image.name}}:{{.Values.image.version}}
    imagePullPolicy: Always
  restartPolicy: Always
