---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jetstream-controller-cluster-role
  namespace: default
rules:
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update
  - delete
- apiGroups:
  - jetstream.nats.io
  resources:
  - streams
  - streams/status
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update
  - delete

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jetstream-controller-service-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jetstream-controller-cluster-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: jetstream-controller-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: jetstream-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
