name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_CLI_TOKEN }}

    - name: Get Image Tags
      id: tags
      run: |
        version=$(sed 's/^v//' <<< ${{ github.ref_name }})
        echo tags="latest,${version}" >> $GITHUB_OUTPUT

    - name: Build and Push
      # 2023-05-07 note: the action documents:
      #   This repository is considered EXPERIMENTAL and under active development
      #   until further notice. It is subject to non-backward compatible changes
      #   or removal in any future version
      # thus while v3.0.1 is the latest, I'm leaving this on v2 for an owner to
      # investigate.
      uses: docker/bake-action@v2
      env:
        TAGS: "${{ steps.tags.outputs.tags }}"
        REGISTRY: "natsio"
      with:
        push: true
        set:
          goreleaser.args.GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

    - name: Attach Release Files
      run: gh release upload ${{ github.ref_name }} deploy/crds.yml deploy/rbac.yml
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
