name: Testing

on:
- push
- pull_request

jobs:
  build:
    name: Testing Job
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Build
      run: make build
    - name: Test
      run: make test
