name: Test
on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Build
      run: make build

    - name: Test
      run: make test
